import { EditorView } from '@codemirror/view';
import { HighlightStyle } from '@codemirror/language';
import { tags } from '@lezer/highlight';

export const myHighlightStyle = HighlightStyle.define([
    { tag: tags.heading1, fontSize: "2em", fontWeight: "bold", borderBottom: "1px solid #eee", display: "inline-block", width: "100%", paddingBottom: "0.3em", marginBottom: "0.5em" },
    { tag: tags.heading2, fontSize: "1.5em", fontWeight: "bold", borderBottom: "1px solid #eee", display: "inline-block", width: "100%", paddingBottom: "0.3em" },
    { tag: tags.heading3, fontSize: "1.25em", fontWeight: "bold" },
    { tag: tags.heading, fontWeight: "bold" },
    { tag: tags.strong, fontWeight: "bold" },
    { tag: tags.emphasis, fontStyle: "italic" },
    { tag: tags.monospace, backgroundColor: "rgba(27, 31, 35, 0.05)", borderRadius: "3px", padding: "0.2em 0.4em", fontFamily: "monospace" },
    { tag: tags.link, color: "#0366d6", textDecoration: "underline" },
    { tag: tags.list },
    { tag: tags.quote, borderLeft: "4px solid #dfe2e5", paddingLeft: "1em", color: "#6a737d", fontStyle: "italic" }, // Blockquote
]);

export const baseTheme = EditorView.theme({
    "&": {
        height: "100%",
        fontSize: "16px",
        fontFamily: "'Inter', sans-serif"
    },
    ".cm-scroller": { fontFamily: "inherit" },
    ".cm-content": {
        padding: "40px 60px", // Typora-like padding
        maxWidth: "900px",
        margin: "0 auto",
    },
    "&.cm-focused": { outline: "none" },
    ".cm-blockquote-line": {
        borderLeft: "4px solid #dfe2e5",
        paddingLeft: "1em",
        color: "#6a737d",
        fontStyle: "italic"
    },
    ".cm-fenced-code-line": {
        backgroundColor: "#f6f8fa",
        padding: "0.5em 1em",
        borderRadius: "4px",
        fontFamily: "monospace",
        fontSize: "0.9em",
        lineHeight: "1.5"
    },
    
    // --- Autocomplete Tooltip Styling ---
    ".cm-tooltip": {
        border: "none",
        backgroundColor: "#ffffff",
        borderRadius: "8px",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15), 0 0 1px rgba(0,0,0,0.1)",
        padding: "4px 0",
        overflow: "hidden"
    },
    ".cm-tooltip-autocomplete": {
        "& > ul": {
            fontFamily: "'Inter', sans-serif",
            whiteSpace: "nowrap",
            overflow: "hidden auto",
            maxWidth: "700px",
            minWidth: "250px",
            maxHeight: "10em",
            "& > li": {
                padding: "6px 12px",
                lineHeight: "1.4",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                gap: "8px"
            },
            "& > li[aria-selected]": {
                backgroundColor: "#e8f0fe", // Light blue selection
                color: "#1a73e8"
            },
            "& > li:hover": {
                backgroundColor: "#f5f5f5"
            }
        }
    },
    ".cm-completionLabel": {
        fontWeight: "500"
    },
    ".cm-completionDetail": {
        color: "#888",
        fontStyle: "normal",
        fontSize: "0.85em",
        marginLeft: "auto" // Push detail to the right
    },
    
    // --- Completion Icons (Heading Levels) ---
    ".cm-completionIcon": {
        marginRight: "8px",
        width: "20px",
        textAlign: "center",
        display: "inline-block"
    },
    
    // Custom icons for Heading Levels (generated by type: "H1", "H2" etc)
    ".cm-completionIcon-H1": { 
        "&:after": { content: "'H1'" },
        backgroundColor: "#e53935", color: "white", 
        fontSize: "9px", borderRadius: "3px", padding: "2px 4px", fontWeight: "bold", verticalAlign: "middle"
    },
    ".cm-completionIcon-H2": { 
        "&:after": { content: "'H2'" },
        backgroundColor: "#fb8c00", color: "white", 
        fontSize: "9px", borderRadius: "3px", padding: "2px 4px", fontWeight: "bold", verticalAlign: "middle"
    },
    ".cm-completionIcon-H3": { 
        "&:after": { content: "'H3'" },
        backgroundColor: "#fdd835", color: "black", 
        fontSize: "9px", borderRadius: "3px", padding: "2px 4px", fontWeight: "bold", verticalAlign: "middle"
    },
    ".cm-completionIcon-H4": { 
        "&:after": { content: "'H4'" },
        backgroundColor: "#43a047", color: "white", 
        fontSize: "9px", borderRadius: "3px", padding: "2px 4px", fontWeight: "bold", verticalAlign: "middle"
    },
    ".cm-completionIcon-H5": { 
        "&:after": { content: "'H5'" },
        backgroundColor: "#1e88e5", color: "white", 
        fontSize: "9px", borderRadius: "3px", padding: "2px 4px", fontWeight: "bold", verticalAlign: "middle"
    },
    ".cm-completionIcon-H6": { 
        "&:after": { content: "'H6'" },
        backgroundColor: "#8e24aa", color: "white", 
        fontSize: "9px", borderRadius: "3px", padding: "2px 4px", fontWeight: "bold", verticalAlign: "middle"
    },
    
    ".cm-completionIcon-keyword": { // Fallback
        display: "none"
    }
});
